XTZ:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 60
    discordBotKey: <UNIQUE KEY>
    guildId: <UNIQUE GUILD ID>
    contractAddress: <quipuswap contract address>
    tezosNode: <tezos node address>
    stablecoinPeg: False